공지사항 댓글 조회
Liberty52/auth pull request #123
Opened 2023-11-03 17:10 UTC by DryRains

## 스프린트 넘버  : 7
### 백로그 이름 : 공지에서 댓글기능 READ

***
### 작업
1. 조회 관련 Controller, Service, Repository 작업
2. Pageable 적용

**API**

```
GET /notices/{noticeId}/comments?page={페이지번호}&size={사이즈}&sort={정렬기준필드명},{정렬방식}
* 0페이지가 1페이지임
* 예시 URL = http://localhost:8080/notices/NOTICE-001/comments?page=0&size=5&sort=createdAt,desc

<Response>
Status : 200(성공),404(없는 공지사항),500(잘못된 pageable 요청)
Body : {
    "content": [
        {
            "commentId": "c02c1b40-7286-418f-a110-99df48b9212f",
            "noticeId": "NOTICE-001",
            "writerId": "TESTER-001",
            "writerName": "김테스터",
            "writerEmail": "test@gmail.com",
            "content": "댓글이에요5",
            "createdAt": "2023-11-04T02:01:29.270715",
            "updatedAt": null
        },
        {
            "commentId": "3640fbd3-6d4b-4159-83a1-a8378487559c",
            "noticeId": "NOTICE-001",
            "writerId": "TESTER-001",
            "writerName": "김테스터",
            "writerEmail": "test@gmail.com",
            "content": "댓글이에요4",
            "createdAt": "2023-11-04T02:01:26.759",
            "updatedAt": null
        },
        {
            "commentId": "10a7b973-53bb-41d7-a4b9-d38bbfc8e50b",
            "noticeId": "NOTICE-001",
            "writerId": "TESTER-001",
            "writerName": "김테스터",
            "writerEmail": "test@gmail.com",
            "content": "댓글이에요3",
            "createdAt": "2023-11-04T02:01:23.105506",
            "updatedAt": null
        },
        {
            "commentId": "bfe640ab-c09e-4329-a736-55af22022f97",
            "noticeId": "NOTICE-001",
            "writerId": "TESTER-001",
            "writerName": "김테스터",
            "writerEmail": "test@gmail.com",
            "content": "댓글이에요2",
            "createdAt": "2023-11-04T02:01:20.379802",
            "updatedAt": null
        },
        {
            "commentId": "294ff417-1677-46bd-9781-3a3f8b1a7957",
            "noticeId": "NOTICE-001",
            "writerId": "TESTER-001",
            "writerName": "김테스터",
            "writerEmail": "test@gmail.com",
            "content": "댓글이에요1",
            "createdAt": "2023-11-04T02:01:17.698397",
            "updatedAt": null
        }
    ],
    "pageable": {
        "sort": [
            {
                "direction": "DESC",
                "property": "createdAt",
                "ignoreCase": false,
                "nullHandling": "NATIVE",
                "descending": true,
                "ascending": false
            }
        ],
        "offset": 0,
        "pageSize": 5,
        "pageNumber": 0,
        "paged": true,
        "unpaged": false
    },
    "last": false,
    "totalElements": 14,
    "totalPages": 3,
    "first": true,
    "size": 5,
    "number": 0,
    "sort": [
        {
            "direction": "DESC",
            "property": "createdAt",
            "ignoreCase": false,
            "nullHandling": "NATIVE",
            "descending": true,
            "ascending": false
        }
    ],
    "numberOfElements": 5,
    "empty": false
}  
```

***
### 테스트 결과
![image](https://github.com/Liberty52/auth/assets/96376539/3cfeb85e-7c3d-45cf-9fd8-5b0b433d1ef3)

2023-11-04 03:23 UTC, ImKunYoung commented
dang

2023-11-04 05:07 UTC, ImKunYoung commented
![image](https://github.com/Liberty52/auth/assets/46955032/c7b265ae-5f88-413b-94f1-e1b7bfec1939)

2023-11-04 09:58 UTC, parkcoldroad requested changes
CI 로그를 보니까 `NoticeCommentControllerTest` 에서 `NoticeCommentRetrieveService` 클래스를 주입받지 못해서 에러가 뜨는 듯 합니다!
위 클래스에 
``` java
	@MockBean
	private NoticeCommentRetrieveService noticeCommentRetrieveService;
```
이렇게 추가하면 해결될 것 같습니다!

2023-11-04 16:14 UTC, DryRains commented
> ```java
> @MockBean
> 	private NoticeCommentRetrieveService noticeCommentRetrieveService;
> ```

와 커밋을 잘못했는지 로컬에서는 주입이 되어있는데 여기선 안되어있네요..? 너무 든든합니다 고마워요ㅜㅜㅜ

2023-11-05 04:59 UTC, parkcoldroad approved these changes
LGTM !!

2023-11-05 05:56 UTC, merged